/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfeapp;

/**
 *
 * @author ASUS
 */
public class FirstScreen extends javax.swing.JFrame {

    /**
     * Creates new form FirstScreen
     */
    public FirstScreen() {
        initComponents();
        this.setSize(362, 482);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.setBorderPainted(false);
        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setkBackGroundColor(new java.awt.Color(102, 0, 204));
        login.setkBorderRadius(30);
        login.setkEndColor(new java.awt.Color(102, 0, 204));
        login.setkHoverColor(new java.awt.Color(51, 0, 255));
        login.setkHoverEndColor(new java.awt.Color(102, 0, 204));
        login.setkHoverForeGround(new java.awt.Color(255, 153, 102));
        login.setkHoverStartColor(new java.awt.Color(255, 153, 102));
        login.setkPressedColor(new java.awt.Color(255, 255, 255));
        login.setkSelectedColor(new java.awt.Color(0, 0, 0, 1));
        login.setkStartColor(new java.awt.Color(255, 153, 102));
        login.setOpaque(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(40, 250, 290, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login-template1.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(362, 482));
        jLabel1.setMinimumSize(new java.awt.Dimension(362, 482));
        jLabel1.setPreferredSize(new java.awt.Dimension(362, 482));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -80, 362, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       Login login=new Login ();             
             login.setVisible(true);
             this.hide();
             
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private keeptoo.KButton login;
    // End of variables declaration//GEN-END:variables
}
