/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfeapp;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {
public static String driver = "org.gjt.mm.mysql.Driver";

    /**
     * Creates new form Login
     */

  
    public Login() {
        initComponents();
         this.setSize(362, 482);
        this.setResizable(false);
        mail.setText("Email");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mail = new javax.swing.JTextField();
        mdp = new javax.swing.JPasswordField();
        connection = new keeptoo.KButton();
        cancel = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(362, 480));
        getContentPane().setLayout(null);

        mail.setBackground(new java.awt.Color(255, 204, 255));
        mail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mail.setForeground(new java.awt.Color(153, 153, 153));
        mail.setText("Email");
        mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        mail.setOpaque(false);
        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFocusLost(evt);
            }
        });
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        getContentPane().add(mail);
        mail.setBounds(40, 200, 270, 30);

        mdp.setBackground(new java.awt.Color(255, 204, 255));
        mdp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mdp.setForeground(new java.awt.Color(153, 153, 153));
        mdp.setText("jPasswor");
        mdp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        mdp.setOpaque(false);
        mdp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mdpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mdpFocusLost(evt);
            }
        });
        getContentPane().add(mdp);
        mdp.setBounds(40, 267, 270, 30);

        connection.setBackground(new java.awt.Color(255, 255, 255));
        connection.setText("Connection");
        connection.setBorderPainted(false);
        connection.setFocusPainted(false);
        connection.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        connection.setkBackGroundColor(new java.awt.Color(255, 153, 102));
        connection.setkBorderRadius(20);
        connection.setkEndColor(new java.awt.Color(255, 153, 102));
        connection.setkFillButton(false);
        connection.setkHoverEndColor(new java.awt.Color(255, 153, 102));
        connection.setkHoverForeGround(new java.awt.Color(102, 0, 204));
        connection.setkHoverStartColor(new java.awt.Color(102, 0, 204));
        connection.setkPressedColor(new java.awt.Color(255, 255, 255));
        connection.setkSelectedColor(new java.awt.Color(255, 255, 255));
        connection.setkStartColor(new java.awt.Color(102, 0, 204));
        connection.setOpaque(false);
        connection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionActionPerformed(evt);
            }
        });
        getContentPane().add(connection);
        connection.setBounds(40, 360, 120, 30);

        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.setBorderPainted(false);
        cancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancel.setkBackGroundColor(new java.awt.Color(102, 0, 204));
        cancel.setkBorderRadius(20);
        cancel.setkEndColor(new java.awt.Color(102, 0, 204));
        cancel.setkFillButton(false);
        cancel.setkHoverEndColor(new java.awt.Color(102, 0, 204));
        cancel.setkHoverForeGround(new java.awt.Color(255, 153, 102));
        cancel.setkHoverStartColor(new java.awt.Color(255, 153, 102));
        cancel.setkPressedColor(new java.awt.Color(255, 255, 255));
        cancel.setkSelectedColor(new java.awt.Color(255, 255, 255));
        cancel.setkStartColor(new java.awt.Color(255, 153, 102));
        cancel.setOpaque(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(190, 360, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login-template1.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(362, 482));
        jLabel1.setMinimumSize(new java.awt.Dimension(362, 482));
        jLabel1.setPreferredSize(new java.awt.Dimension(362, 482));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -18, 362, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
         FirstScreen firstScreen=new FirstScreen ();             
         firstScreen.setVisible(true);
         this.hide();
    }//GEN-LAST:event_cancelActionPerformed

    private void mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusGained
         if (mail.getText().equals("Email"))
       { mail.setText(""); }
         mail.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_mailFocusGained

    private void mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusLost
        if (mail.getText().equals(""))
          { mail.setText("Email");
            mail.setForeground(new Color(153,153,153));}
        else {
            mail.setForeground(new Color(0,0,0)); }
    }//GEN-LAST:event_mailFocusLost

    private void mdpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mdpFocusGained
         mdp.setText("");
         mdp.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_mdpFocusGained

    private void mdpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mdpFocusLost
       mdp.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_mdpFocusLost

    private void connectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionActionPerformed
        String email="";
        String psd="";
        int b=1;
        try{
           email = mail.getText();
            psd = mdp.getText();
            String url = "jdbc:mysql://localhost:3306/pfe?useSSL=false";
            String user = "root";
            String pass = "";
          
            Class.forName(driver).newInstance();
            Connection connection= DriverManager.getConnection(url,user,pass);               
            Statement s= connection.createStatement();     
            ResultSet rs = s.executeQuery("SELECT * FROM utilisateur WHERE (MAIL = '"+email+"' and MDP ='"+psd+"')");
           
           while(rs.next()){
               b=0;
            String mail = rs.getString("MAIL");
            String prenom = rs.getString("PRENOM");
            String capteur = rs.getString("Type_Sensor");
            System.out.println("mail="+mail+"\n");
            System.out.println("prenom="+prenom+"\n");
            System.out.println("capteur="+capteur+"\n");
            Home home = new Home();
           home.setVisible(true);
           home.setname(prenom);
           home.setcapteur(capteur);
             this.hide();
           }
           
           if (b==1)
            JOptionPane.showMessageDialog(this,"Mail not found or Invalid password ");
            
        }                                        
            catch(Exception e1) {   
               System.out.println(e1.getMessage()); 
               JOptionPane.showMessageDialog(this,"Probleme de connexion ");
            }        
    
    }//GEN-LAST:event_connectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton cancel;
    private keeptoo.KButton connection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField mail;
    private javax.swing.JPasswordField mdp;
    // End of variables declaration//GEN-END:variables
}
